Caw21-88: Styling updates to the comparison pages
SU-SWS/caw_profile pull request #29
Opened 2021-10-14 04:10 UTC by jenbreese

# READY FOR REVIEW

# Summary
- Styling to the the comparison table.
- Styling to the comparison checkboxes.
- Set up for the benefits node page.
- The compare plans button should also clear out the previous compare. (It doesn't now)

# Review By (Date)
- 10/25

# Criticality
- Normal

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Add the comparison paragraph to a page.
4. Verify you can compare different medical or dental plans. 
5. Verify you can use the clear selection link (not currently working)
6. Verify that when you do compare more than once you don't get two headings at the top of the table. (you do get two headings)
7. Verify you can compare multiple plans in either Dental or Medical.
8. Verify you cannot compare a dental plan to a medical one.
9. Verify you can scroll the comparison table.

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? Yes. 

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- [CAW21-88](https://stanfordits.atlassian.net/browse/CAW21-88)
- [CAW21-86](https://stanfordits.atlassian.net/browse/CAW21-86)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-10-14 23:17 UTC, pookmish requested changes

2021-10-14 23:17 UTC, pookmish commented on themes/caw_theme/lib/js/benefits.views.js
> +      .addClass('comparison-table--wrapper');
I think this could be accomplished with the view configs.. 
![image](https://user-images.githubusercontent.com/7185045/137407899-d10fab70-5518-4795-a3d1-7756427400db.png)

2021-10-14 23:17 UTC, pookmish commented on themes/caw_theme/lib/js/benefits.views.js
> +      $("<span class='comparison-table--instruct'>You can scroll in the results box to see all the benefit categories avilable.</span>" )
This definitely can be done by editing the table settings and setting the table caption. 
![image](https://user-images.githubusercontent.com/7185045/137407972-a8378191-dd7e-4690-ad89-60435770ff01.png)

2021-10-14 23:17 UTC, pookmish commented on themes/caw_theme/lib/js/benefits.views.js
> +        .prepend('<a href="#">Clear All</a>');
This could be done during the `submit` click handler.

2021-10-18 17:13 UTC, jenbreese commented on themes/caw_theme/lib/js/benefits.views.js
> +      .addClass('comparison-table--wrapper');
It won't let me do it just on the filtered view? I would like to put the class one level lower than where it shows.
<img width="1281" alt="Screen Shot 2021-10-18 at 10 12 04 AM" src="https://user-images.githubusercontent.com/1187335/137777165-647f7d3c-55a6-4439-a2d7-e14eb30bf443.png">

2021-10-18 21:21 UTC, jenbreese commented on themes/caw_theme/lib/js/benefits.views.js
> +      .addClass('comparison-table--wrapper');
@pookmish Is it possible to add the class to one view? It defaults to both views, which makes for it adding the class 3x

2021-10-19 19:36 UTC, jenbreese commented on themes/caw_theme/lib/js/benefits.views.js
> +      .addClass('comparison-table--wrapper');
I couldn't get this to work as I needed only one class.

2021-10-19 19:47 UTC, jenbreese commented on themes/caw_theme/lib/js/benefits.views.js
> +        .prepend('<a href="#">Clear All</a>');
I'm a little stuck on what changes to make so I'll need some help here because I think it is taking to long. I will work on the benefits node page.

2021-10-20 22:40 UTC, jenbreese commented on themes/caw_theme/lib/js/benefits.views.js
> +      .addClass('comparison-table--wrapper');
Got this fixed.

2021-10-20 22:40 UTC, jenbreese commented on themes/caw_theme/lib/js/benefits.views.js
> +        .prepend('<a href="#">Clear All</a>');
It works but you might have feedback to make more elegant.

2021-10-21 21:20 UTC, pookmish approved these changes

2021-10-21 21:31 UTC, merged